[[pages]]
name = "Home"
icon = "ğŸ¡"
path = "pages/page1.py"

[[pages]]
name = "Data Visualization"
icon = "ğŸ“Š"
path = "pages/page2.py"

[[pages]]
name = "Settings"
icon = "âš™ï¸"
path = "pages/page3.py"
